config/routes.rb
Assoc::Application.routes.draw do

  root to: 'customers#index'

  get 'orders/:id' => 'orders#showone'
  get 'allorders' => 'orders#all'
  
  resources :orders

  resources :customers do
    resources :orders
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :id, :city, :name
  has_many :orders, :dependent => :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :orderdate, :orderitem, :quantity, :customer_id
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

before_filter :find_customer, except: [:all, :showone]

  # GET /orders
  # GET /orders.json
  def index
    # @orders = Order.all
    @orders = @customer.orders

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  
  def all
    @orders = Order.all

    respond_to do |format|
      format.html 
      format.json { render json: @orders }
    end
  end

  
  
  def showone
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # { render 'show' }
      format.json { render json: @order }
    end
  end  
  
  
  # GET /orders/1
  # GET /orders/1.json
  def show
    #@order = Order.find(params[:id])
    @order = @customer.orders.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end


  
  # GET /orders/new
  # GET /orders/new.json
  def new

    @order = @customer.orders.build 
    # @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  
  # GET /orders/1/edit
  def edit
    # @order = Order.find(params[:id])
    @order = @customer.orders.find(params[:id])
  end

  
  
  # POST /orders
  # POST /orders.json
  def create
    #@order = Order.new(params[:order])
    @order = @customer.orders.build(params[:order])

    respond_to do |format|
      if @order.save
        #format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.html { redirect_to [@customer, @order], notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  
  
  # PUT /orders/1
  # PUT /orders/1.json
  def update
    #@order = Order.find(params[:id])
    @order = @customer.orders.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to [@customer, @order], notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  
  
  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    #@order = Order.find(params[:id])
    @order = @customer.orders.find(params[:id])
    @order.destroy

    respond_to do |format|
      #format.html { redirect_to orders_url }
      format.html { redirect_to customer_orders_path(@customer) }
      format.json { head :no_content }
    end
  end
 


 
  private
  def find_customer
    @customer = Customer.find(params[:customer_id])
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to t(customer.id),
                      customer_path(customer), :class => 'btn btn-mini' %></td>
        <td><%= customer.name %></td>
        <td><%= customer.city %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @customer.city %></dd>
</dl>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>


<p>
	<%= render :partial => "orders/orders_per_customer" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Assoc" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Assoc</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for ([@customer,@order]), :html => { :class => 'form-horizontal' }  do |f| %>
  <div class="control-group">
    <%= f.label :orderitem, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :orderitem, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :quantity, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :quantity, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :orderdate, :class => 'control-label' %>
    <div class="controls">
	<%= f.date_select :orderdate, {:prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' }}, {:class => 'date-select'}  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :customer_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :customer_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customer_path(@customer), :class => 'btn' %>
  </div>
<% end %>

app/views/orders/_orders_per_customer.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<table class="table table-striped">
	<thead>
	  <tr>
	    <th><%= model_class.human_attribute_name(:customer_id) %></th>
	    <th><%= model_class.human_attribute_name(:orderitem) %></th>
	    <th><%= model_class.human_attribute_name(:quantity) %></th>
	    <th><%= model_class.human_attribute_name(:orderdate) %></th>
		<th><%= model_class.human_attribute_name(:created_at) %></th>
	    <th><%=t '.actions', :default => t("helpers.actions") %></th>
	  </tr>
	</thead>
  <tbody>	
	<% @customer.orders.each do |order| %>
	  <tr>
	    <td><%= @customer.id %></td>
	    <td><%= link_to order.orderitem, customer_order_path(@customer,order) %></td>
	    <td><%= order.quantity %></td>
	    <td><%= order.orderdate %></td>
        <td><%=l order.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_order_path(@customer,order), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_order_path(@customer,order),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>  
        </td>
	  </tr>
	<% end %>
  </tbody>
</table>

<br />


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_order_path(@customer) ,
            :class => 'btn btn-primary' %>

app/views/orders/all.html.erb
#  link_to "Label", :controller => :my_controller, :action => :index


<h1>Listing orders</h1>

<table>
  <tr>
    <th>Customer Id</th>
    <th>Order Item</th>
    <th>Quantity</th>
    <th>Order Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.customer_id %></td>
    <td><%= order.orderitem %></td>
    <td><%= order.quantity %></td>
    <td><%= order.orderdate %></td>
    <td><%= link_to 'Show', order_path(order), :action => 'showone' %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

	<%= link_to 'New Order', new_order_path %>

<br />

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:orderitem) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:orderdate) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order_path(order) %></td>
        <td><%= order.orderitem %></td>
        <td><%= order.quantity %></td>
        <td><%= order.orderdate %></td>
        <td><%= order.customer_id %></td>
        <td><%=l order.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_path(order), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_path(order),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_path,
            :class => 'btn btn-primary' %>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:orderitem) %>:</strong></dt>
  <dd><%= @order.orderitem %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @order.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orderdate) %>:</strong></dt>
  <dd><%= @order.orderdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @order.customer_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customer_path(@customer), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_order_path(@customer,@order), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_order_path(@customer,@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/orders/showone.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order Item:</b>
  <%= @order.orderitem %>
</p>

<p>
  <b>Quantity:</b>
  <%= @order.quantity %>
</p>

<p>
  <b>Order Date:</b>
  <%= @order.orderdate %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', allorders_path %>